// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdB2e5EUB0Lo_Jljqa3qgz_qSFt_wOWzw',
    appId: '1:230012424872:web:21781df980786aef85e89d',
    messagingSenderId: '230012424872',
    projectId: 'lyriscope-27e45',
    authDomain: 'lyriscope-27e45.firebaseapp.com',
    storageBucket: 'lyriscope-27e45.firebasestorage.app',
    measurementId: 'G-BRLB5W1V4T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw9m6CACajewqp6I2tQjBvezveuqw_nC8',
    appId: '1:230012424872:android:ea7ab338bd4599d985e89d',
    messagingSenderId: '230012424872',
    projectId: 'lyriscope-27e45',
    storageBucket: 'lyriscope-27e45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAarvs8rVOdBNOoyFz2WME4hkVTjIhu7oQ',
    appId: '1:230012424872:ios:ebc52dea44a5b84a85e89d',
    messagingSenderId: '230012424872',
    projectId: 'lyriscope-27e45',
    storageBucket: 'lyriscope-27e45.firebasestorage.app',
    iosBundleId: 'com.example.lyriscope',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAarvs8rVOdBNOoyFz2WME4hkVTjIhu7oQ',
    appId: '1:230012424872:ios:ebc52dea44a5b84a85e89d',
    messagingSenderId: '230012424872',
    projectId: 'lyriscope-27e45',
    storageBucket: 'lyriscope-27e45.firebasestorage.app',
    iosBundleId: 'com.example.lyriscope',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdB2e5EUB0Lo_Jljqa3qgz_qSFt_wOWzw',
    appId: '1:230012424872:web:88fe88d387eed01985e89d',
    messagingSenderId: '230012424872',
    projectId: 'lyriscope-27e45',
    authDomain: 'lyriscope-27e45.firebaseapp.com',
    storageBucket: 'lyriscope-27e45.firebasestorage.app',
    measurementId: 'G-49JK3RK0Q2',
  );
}
